// src/components/CookiePolicy.jsx
import React, { useEffect } from 'react';

export default function CookiePolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="w-full min-h-screen flex flex-col items-center bg-surface pt-32 pb-16 px-4">
      <div className="w-full max-w-3xl bg-white rounded-2xl shadow-lg p-8 md:p-12">
        <h1 className="text-3xl font-bold text-accent mb-2">Cookie Policy</h1>
        <div className="text-xs text-dark/50 mb-6 pb-4 border-b border-dark/10">Last updated: June 2025</div>
        <div className="flex flex-col gap-8">
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Introduction</h2>
            <p className="text-base text-dark/80 leading-relaxed">Our website uses cookies to distinguish you from other users of our website. This helps us to provide you with a good experience when you browse our website and also allows us to improve our site. By continuing to browse the site, you are agreeing to our use of cookies.</p>
            <p className="text-base text-dark/80 leading-relaxed">Please read this Cookie Policy carefully as it contains important information on who we are and how we use cookies on our website.</p>
            <p className="text-base text-dark/80 leading-relaxed">This Policy should be read together with our Privacy Policy which sets out how and why we collect, store, use and share personal information generally, as well as your rights in relation to your personal information and details of how to contact us and supervisory authorities if you have a complaint.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Our Website</h2>
            <p className="text-base text-dark/80 leading-relaxed">This Cookie Policy relates to your use of our website <a href="https://untether.group" target="_blank" rel="noopener noreferrer" className="text-accent underline">https://untether.group</a>.</p>
            <p className="text-base text-dark/80 leading-relaxed">Throughout our website we may link to other websites owned and operated by certain trusted third parties to make additional products and services available to you. These other third party websites may also use cookies or similar technologies in accordance with their own separate polices. For privacy information relating to these other third party websites, please consult their policies as appropriate.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Cookies and Similar Technology</h2>
            <p className="text-base text-dark/80 leading-relaxed">Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology.</p>
            <p className="text-base text-dark/80 leading-relaxed">Untether Ltd. uses cookies in a range of ways to improve your experience on our website, including:</p>
            <ul className="list-disc pl-6 text-dark/80 mb-2">
              <li>keeping you signed in</li>
              <li>understanding how you use our website</li>
            </ul>
            <p className="text-base text-dark/80 leading-relaxed">For example, we may monitor how many times you visit the website, which pages you go to, traffic data, location data and the originating domain name of your internet service provider. This information helps us to build a profile of our users. Some of this data will be aggregated or statistical, which means that we will not be able to identify you individually.</p>
            <p className="text-base text-dark/80 leading-relaxed">We use the following cookies:</p>
            <ul className="list-disc pl-6 text-dark/80 mb-2">
              <li><b>Strictly necessary cookies.</b> These are cookies that are required for the operation of our website. They include, for example, cookies that enable you to log into secure areas of our website, use a shopping cart or make use of e-billing services.</li>
              <li><b>Analytical/performance cookies.</b> They allow us to recognise and count the number of visitors and to see how visitors move around our website when they are using it. This helps us to improve the way our website works, for example, by ensuring that users are finding what they are looking for easily.</li>
              <li><b>Functionality cookies.</b> These are used to recognise you when you return to our website. This enables us to personalise our content for you, greet you by name and remember your preferences (for example, your choice of language or region).</li>
              <li><b>Targeting cookies.</b> These cookies record your visit to our website, the pages you have visited and the links you have followed. We will use this information to make our website and the advertising displayed on it more relevant to your interests. We may also share this information with third parties for this purpose.</li>
            </ul>
            <p className="text-base text-dark/80 leading-relaxed">If you disable or refuse cookies, please note that some parts of this website may become inaccessible or not function properly.</p>
            <p className="text-base text-dark/80 leading-relaxed">For further information, visit <a href="https://www.allaboutcookies.org" target="_blank" rel="noopener noreferrer" className="text-accent underline">https://www.allaboutcookies.org</a>.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Consent to use cookies and changing settings</h2>
            <p className="text-base text-dark/80 leading-relaxed">We will ask for your permission ("Consent") to place cookies or other similar technologies on your device, except where they are essential for us to provide you with a service that you have requested. You can withdraw any consent to the use of cookies or manage any other cookie preferences.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Our use of cookies</h2>
            <p className="text-base text-dark/80 leading-relaxed">The tables below provide you can find more information about the individual cookies we use and the purposes for.</p>
            <div className="overflow-x-auto my-4 rounded-lg shadow">
              <table className="w-full border-collapse bg-white text-sm">
                <thead>
                  <tr>
                    <th className="bg-surface font-bold text-dark border-b border-dark/10 px-3 py-2">Cookie</th>
                    <th className="bg-surface font-bold text-dark border-b border-dark/10 px-3 py-2">Type</th>
                    <th className="bg-surface font-bold text-dark border-b border-dark/10 px-3 py-2">Description</th>
                    <th className="bg-surface font-bold text-dark border-b border-dark/10 px-3 py-2">Duration</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">_gid</td>
                    <td className="border-b border-dark/10 px-3 py-2">Analytics</td>
                    <td className="border-b border-dark/10 px-3 py-2">This cookie is set by Google Analytics. It stores and update a unique value for each page visited and is used to count and track pageviews.</td>
                    <td className="border-b border-dark/10 px-3 py-2">1 day</td>
                  </tr>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">_ga_JYK8FDQ76Z</td>
                    <td className="border-b border-dark/10 px-3 py-2">Analytics</td>
                    <td className="border-b border-dark/10 px-3 py-2">This cookie is installed by Google Analytics.</td>
                    <td className="border-b border-dark/10 px-3 py-2">2 years</td>
                  </tr>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">_ga</td>
                    <td className="border-b border-dark/10 px-3 py-2">Analytics</td>
                    <td className="border-b border-dark/10 px-3 py-2">The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site's analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.</td>
                    <td className="border-b border-dark/10 px-3 py-2">2 years</td>
                  </tr>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">__cf_bm</td>
                    <td className="border-b border-dark/10 px-3 py-2">Functional</td>
                    <td className="border-b border-dark/10 px-3 py-2">This cookie is used to distinguish between humans and bots. This is beneficial for the website, in order to make valid reports on the use of their website.</td>
                    <td className="border-b border-dark/10 px-3 py-2">30 minutes</td>
                  </tr>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">_GRECAPTCHA</td>
                    <td className="border-b border-dark/10 px-3 py-2">Necessary</td>
                    <td className="border-b border-dark/10 px-3 py-2">This cookie is set by the Google recaptcha service to identify bots to protect the website against malicious spam attacks.</td>
                    <td className="border-b border-dark/10 px-3 py-2">6 months</td>
                  </tr>
                  <tr>
                    <td className="border-b border-dark/10 px-3 py-2">_gat</td>
                    <td className="border-b border-dark/10 px-3 py-2">Performance</td>
                    <td className="border-b border-dark/10 px-3 py-2">This cookie name is associated with Google Universal Analytics, according to documentation it is used to throttle the request rate – limiting the collection of data on high traffic sites.</td>
                    <td className="border-b border-dark/10 px-3 py-2">1 minute</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-base text-dark/80 leading-relaxed">Please note that third parties (including, for example, advertising networks and providers of external services like web traffic analysis services) may also use cookies, over which we have no control. These cookies are likely to be analytical/performance cookies or targeting cookies.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">How to turn off all cookies and consequences of doing so</h2>
            <p className="text-base text-dark/80 leading-relaxed">If you do not want to accept any cookies, you may be able to change by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of our site.</p>
            <p className="text-base text-dark/80 leading-relaxed">For further information about cookies and how to disable them please go to the <a href="https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/" target="_blank" rel="noopener noreferrer" className="text-accent underline">guidance</a> on cookies published by the UK Information Commissioner's Office, or <a href="https://www.allaboutcookies.org" target="_blank" rel="noopener noreferrer" className="text-accent underline">https://www.allaboutcookies.org</a>.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">How to contact us</h2>
            <p className="text-base text-dark/80 leading-relaxed">Please contact us if you have any questions about this Cookie Policy or the information we hold about you. If you wish to contact us, please send an email to <a href="mailto:hello@untether.group" className="text-accent underline">hello@untether.group</a> or via the <a href="/#contact" className="text-accent underline">Contact page</a> on our website.</p>
          </section>
          <section>
            <h2 className="text-xl font-bold text-dark mb-2 pb-1 border-b-2 border-accent">Changes to this Policy</h2>
            <p className="text-base text-dark/80 leading-relaxed">This Policy was published in November 2021 and last updated in June 2025. We may change this Policy from time to time, when we do we will inform you via our website.</p>
          </section>
        </div>
      </div>
    </div>
  );
}

// src/components/CookiePolicy.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import Navigation from './Navigation.vue'
import FooterSection from './FooterSection.vue'

onMounted(() => {
  window.scrollTo(0, 0)
})
</script>

<template>
  <div class="legal-page">
    <Navigation />
    <main class="legal-main">
      <div class="container">
        <div class="legal-content">
          <h1>Cookie Policy</h1>
          <div class="last-updated">Last updated: June 2025</div>
          
          <div class="content-section">
            <section>
              <h2>Introduction</h2>
              <p>
                Our website uses cookies to distinguish you from other users of our website. This helps us to provide you with a good experience when you browse our website and also allows us to improve our site. By continuing to browse the site, you are agreeing to our use of cookies.
              </p>
              <p>
                Please read this Cookie Policy carefully as it contains important information on who we are and how we use cookies on our website.
              </p>
              <p>
                This Policy should be read together with our Privacy Policy which sets out how and why we collect, store, use and share personal information generally, as well as your rights in relation to your personal information and details of how to contact us and supervisory authorities if you have a complaint.
              </p>
            </section>

            <section>
              <h2>Our Website</h2>
              <p>
                This Cookie Policy relates to your use of our website <a href="https://untether.group" target="_blank" rel="noopener noreferrer">https://untether.group</a>.
              </p>
              <p>
                Throughout our website we may link to other websites owned and operated by certain trusted third parties to make additional products and services available to you. These other third party websites may also use cookies or similar technologies in accordance with their own separate polices. For privacy information relating to these other third party websites, please consult their policies as appropriate.
              </p>
            </section>

            <section>
              <h2>Cookies and Similar Technology</h2>
              <p>
                Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology.
              </p>
              <p>
                Untether Ltd. uses cookies in a range of ways to improve your experience on our website, including:
              </p>
              <ul>
                <li>keeping you signed in</li>
                <li>understanding how you use our website</li>
              </ul>
              <p>
                For example, we may monitor how many times you visit the website, which pages you go to, traffic data, location data and the originating domain name of your internet service provider. This information helps us to build a profile of our users. Some of this data will be aggregated or statistical, which means that we will not be able to identify you individually.
              </p>
              <p>We use the following cookies:</p>
              <ul>
                <li><strong>Strictly necessary cookies.</strong> These are cookies that are required for the operation of our website. They include, for example, cookies that enable you to log into secure areas of our website, use a shopping cart or make use of e-billing services.</li>
                <li><strong>Analytical/performance cookies.</strong> They allow us to recognise and count the number of visitors and to see how visitors move around our website when they are using it. This helps us to improve the way our website works, for example, by ensuring that users are finding what they are looking for easily.</li>
                <li><strong>Functionality cookies.</strong> These are used to recognise you when you return to our website. This enables us to personalise our content for you, greet you by name and remember your preferences (for example, your choice of language or region).</li>
                <li><strong>Targeting cookies.</strong> These cookies record your visit to our website, the pages you have visited and the links you have followed. We will use this information to make our website and the advertising displayed on it more relevant to your interests. We may also share this information with third parties for this purpose.</li>
              </ul>
              <p>
                If you disable or refuse cookies, please note that some parts of this website may become inaccessible or not function properly.
              </p>
              <p>
                For further information, visit <a href="https://www.allaboutcookies.org" target="_blank" rel="noopener noreferrer">https://www.allaboutcookies.org</a>.
              </p>
            </section>

            <section>
              <h2>Consent to use cookies and changing settings</h2>
              <p>
                We will ask for your permission ("Consent") to place cookies or other similar technologies on your device, except where they are essential for us to provide you with a service that you have requested. You can withdraw any consent to the use of cookies or manage any other cookie preferences.
              </p>
            </section>

            <section>
              <h2>Our use of cookies</h2>
              <p>
                The tables below provide you can find more information about the individual cookies we use and the purposes for.
              </p>
              
              <div class="cookie-table">
                <table>
                  <thead>
                    <tr>
                      <th>Cookie</th>
                      <th>Type</th>
                      <th>Description</th>
                      <th>Duration</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>_gid</td>
                      <td>Analytics</td>
                      <td>This cookie is set by Google Analytics. It stores and update a unique value for each page visited and is used to count and track pageviews.</td>
                      <td>1 day</td>
                    </tr>
                    <tr>
                      <td>_ga_JYK8FDQ76Z</td>
                      <td>Analytics</td>
                      <td>This cookie is installed by Google Analytics.</td>
                      <td>2 years</td>
                    </tr>
                    <tr>
                      <td>_ga</td>
                      <td>Analytics</td>
                      <td>The _ga cookie, installed by Google Analytics, calculates visitor, session and campaign data and also keeps track of site usage for the site's analytics report. The cookie stores information anonymously and assigns a randomly generated number to recognize unique visitors.</td>
                      <td>2 years</td>
                    </tr>
                    <tr>
                      <td>__cf_bm</td>
                      <td>Functional</td>
                      <td>This cookie is used to distinguish between humans and bots. This is beneficial for the website, in order to make valid reports on the use of their website.</td>
                      <td>30 minutes</td>
                    </tr>
                    <tr>
                      <td>_GRECAPTCHA</td>
                      <td>Necessary</td>
                      <td>This cookie is set by the Google recaptcha service to identify bots to protect the website against malicious spam attacks.</td>
                      <td>6 months</td>
                    </tr>
                    <tr>
                      <td>_gat</td>
                      <td>Performance</td>
                      <td>This cookie name is associated with Google Universal Analytics, according to documentation it is used to throttle the request rate – limiting the collection of data on high traffic sites.</td>
                      <td>1 minute</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <p>
                Please note that third parties (including, for example, advertising networks and providers of external services like web traffic analysis services) may also use cookies, over which we have no control. These cookies are likely to be analytical/performance cookies or targeting cookies.
              </p>
            </section>

            <section>
              <h2>How to turn off all cookies and consequences of doing so</h2>
              <p>
                If you do not want to accept any cookies, you may be able to change by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of our site.
              </p>
              <p>
                For further information about cookies and how to disable them please go to the <a href="https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/">guidance</a> on cookies published by the UK Information Commissioner's Office, or <a href="https://www.allaboutcookies.org">https://www.allaboutcookies.org</a>.
              </p>
            </section>

            <section>
              <h2>How to contact us</h2>
              <p>
                Please contact us if you have any questions about this Cookie Policy or the information we hold about you. If you wish to contact us, please send an email to <a href="mailto:hello@untether.group">hello@untether.group</a> or via the Contact page <router-link to="/#contact">https://untether.group/#contact</router-link> on our website.
              </p>
            </section>

            <section>
              <h2>Changes to this Policy</h2>
              <p>
                This Policy was published in November 2021 and last updated in June 2025. We may change this Policy from time to time, when we do we will inform you via our website.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
    <FooterSection />
  </div>
</template>

<style scoped>
.legal-page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.legal-main {
  flex: 1;
  padding: var(--spacing-2xl) 0;
  background-color: var(--background-secondary);
  margin-top: 70px; /* Account for fixed navigation */
}

.legal-content {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  padding: var(--spacing-2xl);
  border-radius: var(--border-radius-lg);
  box-shadow: 0 4px 20px var(--shadow);
}

.legal-content h1 {
  color: var(--primary-color);
  margin-bottom: var(--spacing-sm);
}

.last-updated {
  color: var(--text-light);
  font-size: 0.9rem;
  margin-bottom: var(--spacing-xl);
  padding-bottom: var(--spacing-md);
  border-bottom: 1px solid var(--border);
}

.content-section {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xl);
}

.content-section section {
  margin-bottom: var(--spacing-lg);
}

.content-section h2 {
  color: var(--text-primary);
  font-size: 1.5rem;
  margin-bottom: var(--spacing-md);
  padding-bottom: var(--spacing-xs);
  border-bottom: 2px solid var(--primary-color);
}

.content-section p {
  margin-bottom: var(--spacing-md);
  line-height: 1.7;
  color: var(--text-secondary);
}

.content-section ul {
  margin-bottom: var(--spacing-md);
  padding-left: var(--spacing-lg);
}

.content-section li {
  margin-bottom: var(--spacing-xs);
  line-height: 1.6;
  color: var(--text-secondary);
}

.content-section a {
  color: var(--primary-color);
  text-decoration: none;
  font-weight: var(--font-weight-medium);
}

.content-section a:hover {
  text-decoration: underline;
}

.cookie-table {
  overflow-x: auto;
  margin: var(--spacing-lg) 0;
  border-radius: var(--border-radius);
  box-shadow: 0 2px 8px var(--shadow);
}

.cookie-table table {
  width: 100%;
  border-collapse: collapse;
  background: white;
}

.cookie-table th,
.cookie-table td {
  padding: var(--spacing-sm) var(--spacing-md);
  text-align: left;
  border-bottom: 1px solid var(--border);
}

.cookie-table th {
  background-color: var(--background-secondary);
  font-weight: var(--font-weight-bold);
  color: var(--text-primary);
  font-size: 0.9rem;
}

.cookie-table td {
  color: var(--text-secondary);
  font-size: 0.85rem;
  line-height: 1.5;
}

.cookie-table tr:hover {
  background-color: rgba(58, 89, 209, 0.05);
}

@media (max-width: 768px) {
  .legal-content {
    padding: var(--spacing-lg);
    max-width: 100%;
  }
  
  .legal-main {
    margin-top: 60px;
  }
  
  .content-section h2 {
    font-size: 1.3rem;
  }
  
  .cookie-table {
    font-size: 0.8rem;
  }
  
  .cookie-table th,
  .cookie-table td {
    padding: var(--spacing-xs) var(--spacing-sm);
  }
}

@media (max-width: 480px) {
  .cookie-table th,
  .cookie-table td {
    padding: var(--spacing-xs);
    font-size: 0.75rem;
  }
}
</style>
